# Dom
db.url=jdbc:postgresql://localhost:5433/projet_hotel
db.user=postgres
db.password=postgres

# # Vicky
# db.url=jdbc:postgresql://localhost:5432/projet_hotel
# db.user=postgres
# db.password=admin

# Jordi
# db.url=jdbc:postgresql://localhost:5432/projet_hotel
# db.user=postgres
# db.password=bolo1925